plugins {
    id("top.hendrixshen.magiclib.build.process-resources-plugin")
}

repositories {
    maven {
        name = "FabricMC"
        url = "https://maven.fabricmc.net"
    }
}

dependencies {
    compileOnly("net.fabricmc:fabric-loader:${project.property("dependencies.fabric_loader_version")}")
}
