modLoader = "javafml"
loaderVersion = "*"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''
${mod_description}
'''
logoFile = "icon.png"
authors = "Hendrix-Shen, Plusls"
displayURL = "${mod_homepage}"
displayTest = "NONE"

[[dependencies.${mod_id}]]
modId = "magiclib_minecraft_api"
mandatory=true
versionRange="*"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId = "${malilib_mod_id}"
mandatory=true
versionRange="*"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory=true
versionRange="${minecraft_dependency}"
ordering="NONE"
side="CLIENT"

[[mixins]]
config = "magiclib-malilib-extra.mixins.json"
