# Dependency Versions
dependencies.minecraft_dependency=>=1.21.4- <1.21.5-
dependencies.minecraft_version=1.21.4

# Fabric API 0.118.0+1.21.4
dependencies.api.fabric_version=0.118.0+1.21.4
# Mod Menu 13.0.2
# modmenu-13.0.2.jar
dependencies.api.modmenu_version=13.0.2

# IMBlockerFabric 1.0.24
# imblockerfabric-1.0.24.jar
dependencies.runtime.imblocker_version=1.0.24
# In-Game Account Switcher 9.0.2-alpha.1
# IAS-Fabric-1.21.4-9.0.2-alpha.1.jar
dependencies.runtime.inGameAccountSwitcher_version=WBbjirJP

# Publish properties
publish.game_version=1.21.4
publish.dependencies_list=
