# Dependency Versions
dependencies.forge_version=40.3.10
dependencies.minecraft_dependency=1.18.x
dependencies.minecraft_version=1.18.2

# IMBlocker 5.2.0
# IMBlocker-5.2.0-forge+1.17-1.20.4.jar
dependencies.runtime.imblocker_version=XtyJRPQi
# In-Game Account Switcher 9.0.2
# IAS-Forge-1.18.2-9.0.2.jar
dependencies.runtime.inGameAccountSwitcher_version=wVhfqIMC

# Loom Properties
loom.platform=forge

# Publish properties
publish.game_version=1.18.2
publish.dependencies_list=
