# Dependency Versions
dependencies.forge_version=40.3.10
dependencies.minecraft_dependency=1.18.x
dependencies.minecraft_version=1.18.2

# IMBlocker 5.3.1
# IMBlocker-5.3.1-forge+1.17-1.20.4.jar
dependencies.runtime.imblocker_version=pOgVFoi9
# In-Game Account Switcher 9.0.4
# IAS-Forge-1.18.2-9.0.4.jar
dependencies.runtime.inGameAccountSwitcher_version=Az6PjZ5q

# Loom Properties
loom.platform=forge

# Publish properties
publish.game_version=1.18.2
publish.dependencies_list=
