# Dependency Versions
dependencies.neoforge_version=21.1.145
dependencies.minecraft_dependency=1.21.1
dependencies.minecraft_version=1.21.1

# Malilib 0.2.11
# MaFgLib-0.2.11-mc1.21.1.jar
dependencies.api.malilib_version=0.2.11-mc1.21.1

# BadPackets neo-0.8.1
# badpackets-neo-0.8.1.jar
dependencies.api.badpackets_version=neo-0.8.1

# Loom Properties
loom.platform=neoforge

# Publish properties
publish.game_version=1.21.1
publish.dependencies_list=\
  mafglib(optional){modrinth:SKI34J7B}{curseforge:910766}#(ignore:github)
