# Dependency Versions
dependencies.minecraft_dependency=>=1.21.5- <1.21.6-
dependencies.minecraft_version=1.21.5-rc1

# Malilib 0.23.999-rc1
# malilib-1.21.5-rc1-0.23.999-rc1
dependencies.api.malilib_version=1.21.5-rc1-0.23.999-rc1
dependencies.api.malilib_version.use_sakura_fork=true

# Publish properties
publish.game_version=1.21.5
publish.dependencies_list=\
  malilib(optional){modrinth:GcWjdA9I}{curseforge:303119}#(ignore:github)
