[plugins]
essential-loom-remap = { id = "gg.essential.loom-remap", version.ref = "essential-loom" }
essential-loom-no-remap = { id = "gg.essential.loom-no-remap", version.ref = "essential-loom" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }
preprocessor = { id = "com.replaymod.preprocess", version.ref = "preprocessor" }
replace-token = { id = "top.hendrixshen.replace-token", version.ref = "replace-token" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
yamlang = { id = "me.fallenbreath.yamlang", version.ref = "yamlang" }

[versions]
asm = "9.10.1"
checkstyle = "13.8.0"
commons-lang3 = "3.20.0"
essential-loom = "1.15.50"
fabric-loader = "0.19.4"
grgit = "5.3.3"
gson = "2.14.0"
guava = "33.7.1-jre"
jetbrains-annotations = "26.1.0"
log4j = "2.26.1"
lombok = "1.18.46"
mixinextras = "0.5.4"
preprocessor = "4c38783"
replace-token = "1.2.0"
shadow = "9.6.1"
spongepowered-mixin = "0.8.7"
yamlang = "1.5.0"

[libraries]
# ASM
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }

# Mixin
spongepowered-mixin = { module = "org.spongepowered:mixin", version.ref = "spongepowered-mixin" }
fabric-mixin = "net.fabricmc:sponge-mixin:0.17.4+mixin.0.8.7"

# Mixin Extras
mixinextras-common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }
mixinextras-fabric = { module = "io.github.llamalad7:mixinextras-fabric", version.ref = "mixinextras" }

# Fabric Loader
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

# Plugin
essential-loom = { module = "gg.essential.loom:gg.essential.loom.gradle.plugin", version.ref = "essential-loom" }
preprocessor = { module = "com.github.Fallen-Breath:preprocessor", version.ref = "preprocessor" }
replace-token = { module = "top.hendrixshen.replace-token:top.hendrixshen.replace-token.gradle.plugin", version.ref = "replace-token" }
shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }

# Other
checkstyle = { module = "com.puppycrawl.tools:checkstyle", version.ref = "checkstyle" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

[bundles]
asm = ["asm", "asm-analysis", "asm-commons", "asm-tree", "asm-util"]
