# Dependency Versions
dependencies.minecraft_dependency=~26.1-

# Loom Properties
loom.ignoreDependencyLoomVersionValidation=true

# Publish properties
publish.game_version=26.1,26.1.1,26.1.2
publish.dependencies_list=\
  carpet(optional){modrinth:TQTTVgYE}{curseforge:349239}#(ignore:github),\
  malilib(optional){modrinth:GcWjdA9I}{curseforge:303119}#(ignore:github)
