import net.fabricmc.loom.util.ModPlatform

plugins {
    id("checkstyle")
    id("java")
    id("java-library")
    id("maven-publish")
    id("signing")

    alias(libs.plugins.yamlang)
    alias(libs.plugins.replace.token)

    id("top.hendrixshen.magiclib.build-logic.magic-loom")
    id("top.hendrixshen.magiclib.build-logic.process-resources-minecraft")
}

final int mcVersion = magic.projectDetail.get().getMinecraftVersionNumber()
final ModPlatform modPlatform = magic.projectDetail.get().getPlatform()
final boolean fabricLike = !modPlatform.isForgeLike()
final boolean forgeLike = modPlatform.isForgeLike()
final String projectName = project.name.replace("mc-api-", "")
Project betterDev = evaluationDependsOn(":magiclib-better-dev:better-dev-${projectName}")

repositories {
    mavenLocal()

    maven {
        name = "NyanMaven Mirror"
        url = "https://maven.hendrixshen.moe/mirror"
    }

    maven {
        name = "Curse Maven"
        url = "https://www.cursemaven.com"

        content {
            includeGroup("curse.maven")
        }
    }

    maven {
        name = "Modrinth Maven"
        url = "https://api.modrinth.com/maven"

        content {
            includeGroup("maven.modrinth")
        }
    }
}

dependencies {
    // Lombok
    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)

    // MagicLib Core
    api(annotationProcessor(project(path: ":magiclib-core:${modPlatform.id()}", configuration: "shadow")))

    // Dont publish better dev dependencies.
    compileOnly(project(path: betterDev.path, configuration: magic.projectDetail.get().isUnobfuscatedVersion() ? null : "namedElements"))
    localRuntime(project(path: betterDev.path, configuration: magic.projectDetail.get().isUnobfuscatedVersion() ? null : "namedElements"))

    if (forgeLike && !magic.projectDetail.get().isUnobfuscatedVersion()) {
        compileOnly(project(path: betterDev.path, configuration: "modCompileClasspathMainMapped"))
        localRuntime(project(path: betterDev.path, configuration: "modRuntimeClasspathMainMapped"))
    }
}

loom {
    accessWidenerPath.set(file("src/main/resources/${project.parent.property("mod.id")}.accesswidener"))
    enableTransitiveAccessWideners.set(false)

    interfaceInjection {
        enableDependencyInterfaceInjection.set(false)
        isEnabled.set(false)
    }

    runConfigs.named("client") {
        programArgs([
                "--width",
                project.getOrDefault("ow.game.window.width", "1920"),
                "--height",
                project.getOrDefault("ow.game.window.height", "1080"),
                "--username",
                project.getOrDefault("ow.game.username", "dev")
        ])
    }

    if (fabricLike) {
        runs {
            mixinAuditClient {
                inherit(client)
                vmArgs("-Dmagiclib.debug.mixinAuditor.enable=true")
                ideConfigGenerated(false)
                runDir("run/client")
            }

            mixinAuditServer {
                inherit(server)
                vmArgs("-Dmagiclib.debug.mixinAuditor.enable=true")
                ideConfigGenerated(false)
                runDir("run/server")
            }
        }
    }
}

base {
    setArchivesName("${project.parent.property("mod.archives_base_name")}-mc${magic.projectDetail.get().getMinecraftVersionName()}-${modPlatform.id()}")
    setGroup("${project.property("mod.maven_group")}")
    setVersion(project.getModVersion(project.parent))
}

checkstyle {
    configFile = rootProject.file("checkstyle-light.xml")
    toolVersion = libs.versions.checkstyle.get()
}

if (!magic.projectDetail.get().isUnobfuscatedVersion()) {
    remapJar {
        if (forgeLike) {
            if (modPlatform == ModPlatform.NEOFORGE) {
                atAccessWideners.add("${project.parent.property("mod.id")}.accesswidener")
            }
        }
    }
}

replaceToken {
    targetSourceSets.set([sourceSets.main])
    replace("@MOD_IDENTIFIER@", project.parent.property("mod.id").toString().replace("-", "_"))
    replace("@MOD_NAME@"      , project.parent.property("mod.name"))
    replace("@MOD_VERSION@"   , project.getVersionWithCommitHash(this.project.parent) as String)
    replaceIn("top/hendrixshen/magiclib/impl/minecraft/SharedConstants")
    replaceIn("top/hendrixshen/magiclib/entrypoint/minecraft/MagicLibForge")
    replaceIn("top/hendrixshen/magiclib/entrypoint/minecraft/MagicLibNeoForge")
}

yamlang {
    targetSourceSets.set([sourceSets.main])
    inputDir.set("assets/${project.parent.property("mod.id")}/lang")
}

signing {
    String signingKey = project.getOrDefault("secrets.gpg.signingKey", project.getEnv().SIGNING_PGP_KEY)
    String signingPassword = project.getOrDefault("secrets.gpg.signingPassword", project.getEnv().SIGNING_PGP_PASSWORD)
    required = signingKey
    useInMemoryPgpKeys(signingKey, signingPassword ? signingPassword : "")
    sign(publishing.publications)
}

publishing {
    publications { PublicationContainer publications ->
        register("release", MavenPublication) { MavenPublication publication ->
            artifactId = "${this.project.parent.property("mod.artifact_name")}-${projectName}"
            from(this.project.components.java)
            version = "${this.project.getMavenArtifactVersion(this.project.parent)}"
            this.project.addPomMetadataInformation(this.project.parent, publication)
        }
    }

    repositories { RepositoryHandler repositoryHandler ->
        mavenLocal {
            name = "mavenLocal"
        }

        maven {
            name = "projectLocalRelease"
            url = "${rootDir}/publish/release"
        }

        maven {
            name = "nyanMavenRelease"
            url = "https://maven.hendrixshen.moe/releases"

            project.credentialsNyanMaven(it)
        }
    }
}

// Solutions from: https://youtrack.jetbrains.com/issue/KT-46466
TaskCollection<Sign> signingTasks = tasks.withType(Sign)
tasks.withType(AbstractPublishToMaven).configureEach {
    dependsOn(signingTasks)
}

tasks.withType(PublishToMavenRepository).configureEach {
    Provider<Boolean> predicate = provider {
        repository == publishing.repositories.mavenLocal ||
                (repository == publishing.repositories.projectLocalRelease && publication == publishing.publications.release) ||
                (repository == publishing.repositories.nyanMavenRelease && publication == publishing.publications.release && project.isNyanMavenCredentialsExist())
    }

    onlyIf {
        predicate.get()
    }
}

tasks.withType(Javadoc).configureEach { Javadoc task ->
    include("**/api/**")
    task.options.encoding = "UTF-8"
    (task.options as CoreJavadocOptions).addStringOption("Xdoclint:none", "-quiet")
}

tasks.register("cleanRuns", Delete.class) { Delete cleanTask ->
    dependsOn("cleanRunClient", "cleanRunServer")
    cleanTask.setGroup("${project.property("mod.id")}")
    cleanTask.delete(file(loom.runConfigs.client.runDir).parentFile)
}

tasks.register("cleanRunClient", Delete.class) { Delete cleanTask ->
    cleanTask.setGroup("${project.property("mod.id")}")
    cleanTask.delete(loom.runConfigs.client.runDir)
}

tasks.register("cleanRunServer", Delete.class) { Delete cleanTask ->
    cleanTask.setGroup("${project.property("mod.id")}")
    cleanTask.delete(loom.runConfigs.server.runDir)
}

tasks.register("cleanJar", Delete.class) { Delete cleanTask ->
    cleanTask.setGroup("${project.property("mod.id")}")
    cleanTask.delete(project.layout.buildDirectory.dir("libs"))
}

[
        "runClient", "runServer",
        "runMixinAuditClient", "runMixinAuditServer",
        "preprocessCode", "preprocessResources",
        "preprocessTestCode", "preprocessTestResources"
].forEach { taskName ->
    if (tasks.getNames().contains(taskName)) {
        tasks.named(taskName) {
            it.setGroup("${project.property("mod.id")}")
        }
    }
}
