# Dependency Versions
dependencies.minecraft_dependency=>=1.21.6- <1.21.7-
dependencies.minecraft_version=1.21.6

# Carpet - 1.4.176+v250617
# fabric-carpet-1.21.6-1.4.176+v250617.jar
dependencies.api.carpet_version=1.21.6-1.4.176+v250617

# Publish properties
publish.game_version=1.21.6
publish.dependencies_list=\
  carpet(optional){modrinth:TQTTVgYE}{curseforge:349239}#(ignore:github),\
  malilib(optional){modrinth:GcWjdA9I}{curseforge:303119}#(ignore:github)
