# Dependency Versions
dependencies.neoforge_version=21.3.80
dependencies.minecraft_dependency=1.21.3
dependencies.minecraft_version=1.21.3

# IMBlocker 5.3.1
# IMBlocker-5.3.1-neoforge-1.20.6+.jar
dependencies.runtime.imblocker_version=CIdH0JQr
# In-Game Account Switcher 9.0.4
# IAS-NeoForge-1.21.3-9.0.4.jar
dependencies.runtime.inGameAccountSwitcher_version=13hMwIl3

# Loom Properties
loom.platform=neoforge

# Publish properties
publish.game_version=1.21.3
publish.dependencies_list=
