# Dependency Versions
dependencies.neoforge_version=21.4.137
dependencies.minecraft_dependency=1.21.4
dependencies.minecraft_version=1.21.4

# Malilib 0.3.3
# MaFgLib-0.3.3-mc1.21.4.jar
dependencies.api.malilib_version=0.3.3-mc1.21.4

# BadPackets neo-0.8.2
# badpackets-neo-0.8.2.jar
dependencies.api.badpackets_version=neo-0.8.2

# Loom Properties
loom.platform=neoforge

# Publish properties
publish.game_version=1.21.4
publish.dependencies_list=\
  mafglib(optional){modrinth:SKI34J7B}{curseforge:910766}#(ignore:github)
