repositories {
    maven {
        name = "NeoForge"
        url = "https://maven.neoforged.net"
    }
}

dependencies {
    compileOnly("net.neoforged.fancymodloader:core:${project.property("dependencies.fancymodloader_version")}")
    compileOnly("net.neoforged.fancymodloader:language-java:${project.property("dependencies.fancymodloader_version")}")
    compileOnly("net.neoforged.fancymodloader:loader:${project.property("dependencies.fancymodloader_version")}")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

processResources {
    inputs.property("mod_description", project.property("mod.description"))
    inputs.property("mod_homepage"   , project.property("mod.homepage"))
    inputs.property("mod_id"         , project.property("mod.id").toString().replace("-", "_"))
    inputs.property("mod_license"    , project.property("mod.license"))
    inputs.property("mod_name"       , project.property("mod.name"))
    inputs.property("mod_version"    , project.getVersionWithCommitHash(this.project.parent))

    filesMatching(["META-INF/mods.toml", "META-INF/neoforge.mods.toml"]) {
        expand([
                "mod_description": inputs.properties.get("mod_description"),
                "mod_homepage"   : inputs.properties.get("mod_homepage"),
                "mod_id"         : inputs.properties.get("mod_id"),
                "mod_license"    : inputs.properties.get("mod_license"),
                "mod_name"       : inputs.properties.get("mod_name"),
                "mod_version"    : inputs.properties.get("mod_version")
        ])
    }

    from("${rootDir}/LICENSE")
    from("${rootDir}/icon.png")

    from("${rootDir}/icon.png") {
        into("assets/${project.parent.property("mod.id")}")
    }
}

tasks.withType(Jar).configureEach {
    manifest.attributes(
            "MixinConfigs": "magiclib-core-bootstrap.mixins.json"
    )
}
