import top.hendrixshen.magiclib.buildLogic.RootMagicLoomExtension

plugins {
    alias(libs.plugins.essential.loom.remap).apply(false)
    alias(libs.plugins.essential.loom.no.remap).apply(false)
    alias(libs.plugins.preprocessor).apply(false)

    id("top.hendrixshen.magiclib.build-logic.magic-loom-root")
}

magic {
    magiclibMode = true
    multiPlatformSupport = true
    extraMappingFailureStrategy = RootMagicLoomExtension.ExtraMappingFailureStrategy.IGNORE
}
