plugins {
    id("top.hendrixshen.magiclib.build.process-resources-plugin")
}

repositories {
    maven {
        name = "Forge"
        url = "https://maven.minecraftforge.net"
    }
}

dependencies {
    compileOnly("net.minecraftforge:forge:${project.property("dependencies.forge_version")}:universal")
    compileOnly("net.minecraftforge:forge:${project.property("dependencies.forge_version")}:launcher")
    compileOnly("net.minecraftforge:forgespi:${project.property("dependencies.forgespi_version")}")
    compileOnly("cpw.mods:modlauncher:${project.property("dependencies.modlauncher_version")}")
    compileOnly("org.apache.maven:maven-artifact:${project.property("dependencies.maven-artifact_version")}")
}

tasks.withType(Jar).configureEach {
    manifest.attributes(
            "MixinConfigs": "magiclib-core-bootstrap.mixins.json"
    )
}
