# Dependency Versions
dependencies.minecraft_dependency=1.21.3
dependencies.minecraft_version=1.21.3

# Malilib 0.3.5
# MaFgLib-0.3.5-mc1.21.3.jar
dependencies.api.malilib_version=0.3.5-mc1.21.3

# BadPackets neo-0.8.2
# badpackets-neo-0.8.2.jar
dependencies.api.badpackets_version=neo-0.8.2

# Loom Properties
loom.platform=neoforge

# Publish properties
publish.game_version=1.21.3
publish.dependencies_list=\
  mafglib(optional){modrinth:SKI34J7B}{curseforge:910766}#(ignore:github)
