# Dependency Versions
dependencies.minecraft_dependency=>=1.21.5- <1.21.6-
dependencies.minecraft_version=1.21.5

# Fabric API 0.121.0+1.21.5
dependencies.api.fabric_version=0.121.0+1.21.5
# Mod Menu 14.0.0-rc.2
# modmenu-14.0.0-rc.2.jar
dependencies.api.modmenu_version=14.0.0-rc.2

# IMBlockerFabric 1.0.24
# imblockerfabric-1.0.24.jar
dependencies.runtime.imblocker_version=1.0.24
# In-Game Account Switcher 9.0.2
# IAS-Fabric-1.21.5-9.0.2.jar
dependencies.runtime.inGameAccountSwitcher_version=96FYffnc

# Publish properties
publish.game_version=1.21.5
publish.dependencies_list=
