name: _step.build
on:
  workflow_call:
    inputs:
      build_publish:
        type: string
        required: true
      build_version_type:
        type: string
        required: true
      target_subproject:
        description: see CI.yml, leave it empty to build all
        type: string
        required: false
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Cache gradle files
        if: ${{ inputs.build_version_type != 'PULL_REQUEST' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.properties', '**/*.accesswidener', 'settings.json') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # TODO: Remove in next major version
      - name: Preprocess Resources
        run: |
          chmod +x gradlew
          ./gradlew preprocessResources
        env:
          BUILD_TYPE: ${{ inputs.build_version_type }}
      - name: Build with gradle
        run: |
          chmod +x gradlew
          if [ -z "${{ inputs.target_subproject }}" ]; then
              echo "Building all subprojects"
              ./gradlew build
          else
              args=$(echo "${{ inputs.target_subproject }}" | tr ',' '\n' | sed 's/$/:build/' | paste -sd ' ')
              echo "Building with arguments=$args"
              ./gradlew $args
          fi
        env:
          BUILD_TYPE: ${{ inputs.build_version_type }}
      - name: Publish with gradle
        if: ${{ inputs.build_publish == 'true' }}
        run: |
          if [ -z "${{ inputs.target_subproject }}" ]; then
              echo "Publishing all subprojects"
              ./gradlew publish
          else
              args=$(echo "${{ inputs.target_subproject }}" | tr ',' '\n' | sed 's/$/:publish/' | paste -sd ' ')
              echo "Publishing with arguments=$args"
              ./gradlew $args
          fi
        env:
          BUILD_TYPE: ${{ inputs.build_version_type }}
          NYAN_MAVEN_PASSWORD: ${{ secrets.NYAN_MAVEN_PASSWORD }}
          NYAN_MAVEN_USERNAME: ${{ secrets.NYAN_MAVEN_USERNAME }}
          SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            */**/build/libs/
            */**/build/tmp/submods/
  summary:
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - name: Checkout the sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build-artifacts
      - name: Make build summary
        # ubuntu-22.04 uses Python 3.10.6
        run: python3 .github/workflows/scripts/summary.py
        env:
          TARGET_SUBPROJECT: ${{ inputs.target_subproject }}
