name: _step.build
on:
  workflow_call:
    inputs:
      build_publish:
        type: boolean
        default: false
        required: false
      build_version_type:
        type: string
        default: 'DEV'
        required: false
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/dev/0.8' }}
      # TODO: Remove in next major version
      - name: Preprocess Resources
        run: gradle preprocessResources --stacktrace
        env:
          BUILD_TYPE: ${{ inputs.build_version_type }}
      - name: Build and publish with gradle
        if: ${{ inputs.build_publish == true }}
        run: gradle build publish --stacktrace
        env:
          BUILD_TYPE: ${{ inputs.build_version_type }}
          NYAN_MAVEN_PASSWORD: ${{ secrets.NYAN_MAVEN_PASSWORD }}
          NYAN_MAVEN_USERNAME: ${{ secrets.NYAN_MAVEN_USERNAME }}
          SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
      - name: Build and publishToMavenLocal with gradle
        if: ${{ inputs.build_publish == false }}
        run: gradle build publishToMavenLocal --stacktrace
        env:
          BUILD_TYPE: ${{ inputs.build_version_type }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: build-artifacts
          path: |
            */**/build/libs/
            */**/build/tmp/submods/
      - name: Upload MavenLocal
        uses: actions/upload-artifact@v6
        with:
          name: Maven Local
          path: ~/.m2/repository/top/hendrixshen/
  summary:
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - name: Checkout the sources
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          name: build-artifacts
          path: build-artifacts
      - name: Make build summary
        run: |
          pip install jproperties
          python .github/workflows/scripts/summary.py
